apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: step-certificates
  namespace: step-certificates
spec:
  template:
    spec:
      initContainers:
        - name: config
          image: docker.io/nginxinc/nginx-unprivileged:mainline
          volumeMounts:
          - mountPath: /home/step/config
            name: config
          - mountPath: /data
            name: init-config
            readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command:
            - bash
            - -c
            - |
              cp /data/* /home/step/config
              sed -i "s/POD_IP/$POD_IP/" /home/step/config/ca.json
      containers:
        - name: proxy
          image: docker.io/nginxinc/nginx-unprivileged:mainline
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx/conf.d
            - name: certs
              mountPath: /etc/nginx/certs
              readOnly: true
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-config
        - name: config
          emptyDir: {}
          configMap: null
        - name: init-config
          configMap:
            name: step-certificates-config
