apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-certificates-ca-password
spec:
  secretStoreRef:
    name: house-vault
    kind: ClusterSecretStore
  target:
    name: step-certificates-ca-password
  dataFrom:
    - extract:
        key: house/step-certificates/step-certificates-ca-password
