apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-certificates-secrets
spec:
  secretStoreRef:
    name: house-vault
    kind: ClusterSecretStore
  target:
    name: step-certificates-secrets
  data:
    - secretKey: intermediate_ca_key
      remoteRef:
        key: house/step-certificates/intermediate-ca-key
